# Homework on Statistical Learning Theory

<b>Deadline:</b> 24.12.2018, 9 a.m. (there would be no soft deadline)

<b>How to hang in?</b> You need to put your Jupyter Notebook to GitHub repo and send link in Telegram to <b>@CroCode</b>

In [ ]:
Katya Bulycheva

### Block №1. Combinatorics and Probability Theory

You can use LaTeX expressions in order to provide formulas: https://en.wikibooks.org/wiki/LaTeX

1) In how many ways can the letters of the word PROBABILITY be rearranged such that all I’s and P’s appear in the middle?

<b>Total:</b> 1 point

In [1]:
So, we have 11 letters and 3 places in the middle and 8 places left.
PROB---LITY
Firsty, I will count the humber of all interations outside of the middle. 
That is 8! and we alson should not to forget that we have 2 letters B, so we should divide by 2!.
Secondly, I will count the number of iterations inside those 3 places in the middle. We have 3 places and 2 same letters, so the number is 3!/2!.
The final formula: 8!3!/2!2!=60480.

SyntaxError: invalid syntax (<ipython-input-1-120193a3ef0a>, line 1)

2) The probability of having defect (at least 1 defective product) in batch of 100 products is 63.2%. Find the probability of having less than 3 defective products in such a batch.

<i>Hint:</i> use idea of Poisson distribution (https://en.wikipedia.org/wiki/Poisson_distribution)

<b>Total:</b> 1.5 points

In [ ]:
Let us assume that the probability of the defect is p.
The probability of 1 or more defects in 100 products = 1-(1-p)^100 = 0.632
=> p=0.0099
=> E(number of defect products) = 100*p=0.99 = lambda

In [2]:
import math

In [10]:
math.exp(-0.99) + 0.99*math.exp(-0.99) + (0.99**2)*math.exp(-0.99)/2

0.9215287725692245

### Block №2. Data Structures and Algorithms

<b><i>NB!</i></b> Here you need to provide solution having minimal memory and runtime complexity in terms of Big O notation.

3) Suggest an algorithm that resets all elements in the column <i>i</i> and the row <i>j</i> of the matrix M to zeros if the element in the <i>(i, j)</i> cell is zero. Provide solution having minimal memory and runtime complexity in terms of Big O notation.

<b>Input:</b> matrix M

<b>Output:</b> modified according to condition matrix M

<b>Total:</b> 2 points

In [7]:
import numpy as np

In [27]:

def resetto0(X): 
    ncols = X.shape[0]
    nrows = X.shape[1]
    X_new = X.copy()
    
    for i in range(ncols) : 
        for j in range(nrows) : 
            if X[i,j] == 0 : 
                X_new[i,:] = 0
                X_new[:,j] = 0
              
    
    return X_new
                    

          
# COMPLEXITY - O(R*C)


In [28]:
M = np.mat ([ [1, 2, 3, 4], 
                [5, 0, 6, 7], 
                 [8, 9, 10, 11],
                 [12, 0, 13, 0],23
                 [14, 15, 16, 17]])
print(M)
resetto0(M)

[[ 1  2  3  4]
 [ 5  0  6  7]
 [ 8  9 10 11]
 [12  0 13  0]
 [14 15 16 17]]


matrix([[ 1,  0,  3,  0],
        [ 0,  0,  0,  0],
        [ 8,  0, 10,  0],
        [ 0,  0,  0,  0],
        [14,  0, 16,  0]])

4) Imagine you have a square picture, each pixel of which can be black or white (you can interpret it as binary matrix). Develop an algorithm for finding the maximum sub-square consisting of only black pixels.

<b>Input:</b> binary matrix M (contains only 0-1 elements)

<b>Output:</b> <i>((a1, b1),(a2, b2))</i> where <i>(a1, b1)</i> and <i>(a2, b2)</i> stay for coordinates of upper-left and lower-right sub-square corners respectively

<b>Total:</b> 2.5 points

In [95]:
M[100500:100502,100500:100503]

matrix([], shape=(0, 0), dtype=int64)

In [69]:
def check0(X):
    if len(np.where(X == 0)[0]) == 0:
        return False
    else: return True

In [96]:
def find_n_square(X, n):
    ncols = X.shape[0]
    nrows = X.shape[1]
    for i in range(ncols-n) : 
        for j in range(nrows-n) :
            if check0(X[i:i+n,j:j+n]) == False: 
                return [[i, j], [i+n, j+n]]
    return False

In [100]:
def find_max_sqare(X):
    n = 0
    found = True
    lim = min(X.shape)
    coord = []
    while found != False and n < lim:
        n += 1
        s = find_n_square(X, n)
        if s != False:
            coord = s
        else: found = s
    return coord

In [210]:
M = np.mat ([ [1, 1, 1, 1], 
                [1, 0, 1, 1], 
                 [1, 1, 1, 1],
                 [1, 1, 0, 1],
                 [1, 1, 1, 1]])
print('answer (in numpy coordinates): ', find_max_sqare(M) )
print(M)

l = find_max_sqare(M)
a1,a2,a3,a4 = l[0][0],l[1][0], l[0][1],l[1][1]
M[a1:a2, a3:a4] = 9
print(M)

answer (in numpy coordinates):  [[2, 0], [4, 2]]
[[1 1 1 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 0 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 1 1]
 [9 9 1 1]
 [9 9 0 1]
 [1 1 1 1]]


In [ ]:
# put your code with comments here

# Memory complexity: ...
# Runtime complexity: ...

5) Imagine series of integer numbers having only 3, 5 or 7 of some power in their factorization (i.e. 1, 3, 5, 7, 9, 15 etc.). Given k you're asked to return k-th number in this series.

<i>Helpful link</i>: https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic

<b>Input:</b> integer number k

<b>Output:</b> k-th number of series

<b>Total:</b> 3 points

In [145]:
def factors(n):
  all_factors = []
  i=2
  while n>1:
    if n%i==0:
      all_factors.append(i)
      n=n/i
      i+=-1
    i+=1
  unique_factors = list(set(all_factors))
  return unique_factors

In [178]:
def kfind(k):
    a = 1
    counter = 1
    while counter < k:
        a+=2 #проверяем только нечетные
        if all(elem in [3,5,7] for elem in factors(a)) == True:
            counter +=1
    return a

In [179]:
kfind(30)

525

In [ ]:
# put your code with comments here

# Memory complexity: ...
# Runtime complexity: ...